# Generated by Django 4.2.7 on 2024-03-30 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', 'myapp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='role',
        ),
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
