# Generated by Django 5.0.4 on 2024-05-04 10:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=254)),
                ('address', models.TextField()),
                ('longitude', models.CharField(max_length=254)),
                ('latitude', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='TransportationPlan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, null=True)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=12, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Available'), (3, 'On Leave')], default=1)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=254)),
                ('label', models.CharField(max_length=254)),
                ('description', models.TextField()),
                ('date_time', models.DateTimeField()),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Denied'), (3, 'Canceled')], default=0)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=32)),
                ('message', models.TextField()),
                ('date_time', models.DateTimeField()),
                ('employees', models.ManyToManyField(to='api.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('license_plate', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('capacity', models.IntegerField()),
                ('fuel_consumption_level', models.IntegerField()),
                ('status', models.IntegerField(choices=[(0, 'Repairing'), (1, 'Available'), (2, 'Delivering'), (3, 'Unavailable')], default=1)),
                ('brand', models.CharField(blank=True, default=None, max_length=32)),
                ('driver', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ship_code', models.CharField(max_length=32)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('time_in', models.TimeField()),
                ('payload', models.IntegerField()),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'In Progress'), (2, 'Completed'), (3, 'Canceled')], default=0)),
                ('delivery_point', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_point', to='api.customer')),
                ('pickup_point', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_point', to='api.customer')),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.transportationplan')),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='IssueVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.IntegerField(null=True)),
                ('request_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.issue')),
                ('vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vehicle')),
            ],
        ),
    ]
