# Generated by Django 5.0.4 on 2024-05-03 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_alter_order_id'),
        ('api', '0001_remove_employee_role_employee_phone'),
    ]

    operations = [
    ]
