# Generated by Django 5.0.4 on 2024-05-04 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_issuevehicle_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuevehicle',
            name='cost',
        ),
    ]
