# Generated by Django 5.0.4 on 2024-05-03 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_employee_role_employee_phone_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Request',
            new_name='Requests',
        ),
        migrations.RenameModel(
            old_name='Request_Vehicle',
            new_name='Requests_Vehicle',
        ),
    ]
