# Generated by Django 5.0.4 on 2024-05-03 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_request_requests_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requests_vehicle',
            name='request_id',
        ),
        migrations.RemoveField(
            model_name='requests_vehicle',
            name='vehicle_id',
        ),

        migrations.DeleteModel(
            name='Requests',
        ),
        migrations.DeleteModel(
            name='Requests_Vehicle',
        ),
    ]
