# Generated by Django 5.0.4 on 2024-05-04 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_issuevehicle_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuevehicle',
            name='cost',
            field=models.IntegerField(default=0),
        ),
    ]
