# Generated by Django 5.0.4 on 2024-05-08 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_issuevehicle_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.IntegerField(choices=[(2, 'Available'), (3, 'On Leave')], default=2),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (2, 'Approved'), (3, 'Denied'), (4, 'Canceled')], default=0),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.IntegerField(choices=[(0, 'Repairing'), (1, 'Delivering'), (2, 'Available'), (3, 'Unavailable')], default=2),
        ),
    ]
