# Generated by Django 5.0.4 on 2024-05-09 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_employee_status_alter_issue_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'permissions': [('supervisor', 'can act as a supervisor')]},
        ),
    ]
