# Generated by Django 5.0.4 on 2024-05-04 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_employee_role_employee_phone_issue_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Warehouse',
        ),
        # migrations.RemoveField(
        #     model_name='employee',
        #     name='role',
        # ),
        # migrations.AddField(
        #     model_name='employee',
        #     name='phone',
        #     field=models.CharField(blank=True, max_length=12, null=True),
        # ),
        migrations.AddField(
            model_name='issuevehicle',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Denied'), (3, 'Canceled')], default=0),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.IntegerField(choices=[(0, 'Repairing'), (1, 'Available'), (2, 'Delivering'), (3, 'Unavailable')], default=1),
        ),
    ]
