# Generated by Django 5.0.1 on 2024-03-11 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_transportationplan_alter_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='plan_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.transportationplan'),
        ),
    ]
