# Generated by Django 4.1.3 on 2024-05-21 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_employee_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
