# Generated by Django 5.0.1 on 2024-03-11 08:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_order_plan_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='plan_id',
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.date(2024, 3, 11)),
        ),
        migrations.AlterField(
            model_name='transportationplan',
            name='date',
            field=models.DateField(default=datetime.date(2024, 3, 11)),
        ),
    ]
