# Generated by Django 5.0.4 on 2024-05-28 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_notification_sender_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'permissions': [('supervisor', 'can act as a supervisor'), ('driver', 'can act as a driver')]},
        ),
    ]
