# Generated by Django 4.2.7 on 2024-03-12 05:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_order_date_alter_transportationplan_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=254)),
                ('address', models.TextField()),
                ('longitude', models.CharField(max_length=254)),
                ('latitude', models.CharField(max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='hasnotification',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='hasnotification',
            name='notification_id',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='creator_id',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='vehicle_license_plate',
            new_name='vehicle',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='warehouse_id',
            new_name='warehouse',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='employee_id',
            new_name='employee',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='plan_id',
            new_name='plan',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='driver_id',
            new_name='driver',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pickup_id',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='status',
        ),
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='employees',
            field=models.ManyToManyField(to='api.employee'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='brand',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.IntegerField(choices=[(0, 'Available'), (1, 'Busy'), (2, 'On Break')], default=0),
        ),
        migrations.AlterField(
            model_name='issue',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='issue',
            name='label',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'In Progress'), (2, 'Complented'), (3, 'Cancel')], default=0),
        ),
        migrations.AlterField(
            model_name='issue',
            name='title',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='payload',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='transportationplan',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='transportationplan',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.IntegerField(choices=[(0, 'Available'), (1, 'Busy'), (2, 'On Break')], default=0),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='DeliveryPoint',
        ),
        migrations.DeleteModel(
            name='HasNotification',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_point',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_id', to='api.customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_point',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_id', to='api.customer'),
        ),
    ]
