# Generated by Django 4.2.7 on 2024-03-12 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_customer_remove_hasnotification_employee_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'In Progress'), (2, 'Complented'), (3, 'Cancel')], db_column='status', default=0),
        ),
    ]
