# Generated by Django 4.2.7 on 2024-03-12 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_order_delivery_point_alter_order_pickup_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='employee',
        ),
        migrations.AddField(
            model_name='order',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.vehicle'),
        ),
    ]
