# Generated by Django 5.0.1 on 2024-03-12 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_order_delivery_id_alter_order_date_and_more'),
        ('api', '0017_order_status_alter_order_date_and_more'),
    ]

    operations = [
    ]
