# Generated by Django 5.0.1 on 2024-03-12 03:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_merge_20240312_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 3, 12, 3, 7, 48, 468275, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='transportationplan',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 3, 12, 3, 7, 48, 467276, tzinfo=datetime.timezone.utc)),
        ),
    ]
