# Generated by Django 5.0.1 on 2024-03-12 03:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_order_date_alter_transportationplan_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 3, 12, 3, 9, 15, 19407, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='transportationplan',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 3, 12, 3, 9, 15, 18407, tzinfo=datetime.timezone.utc)),
        ),
    ]
