# Generated by Django 5.0.1 on 2024-03-12 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_order_date_alter_transportationplan_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transportationplan',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
